### ISSUE TITLE
Local network support 192.168.x.x

### ISSUE THREAD

**Issue by MadLittleMods** [layerssss/devhttps#1]
Add local network support 192.168.x.x.

Running `devhttps 1443 80` should allow for `https://localhost:1443/` or `https://192.168.x.x:1443/`

**Comment by layerssss** [comment]
Hi @MadLittleMods  you should be able to achieve it by `devhttps 1443 80 192.168.1.101` or `devhttps 1443 80 0.0.0.0` (all interfaces).

**Comment by layerssss** [comment]
@MadLittleMods make sure you upgrade `npm update -g`, I've just pushed it today morning.

https://github.com/layerssss/devhttps/commit/8c7b870d38a8175fefd8cbd530e96d2c6f54139c

**Comment by MadLittleMods** [comment]
Was already on v1.0.4 but just made sure I had the latest.

Running with the extra argument shows it using the new `https_bind` but when trying to visit it in the browser, it doesn't respond (works with the default `localhost` though).

``` sh
devhttps 5443 5000 192.168.1.135
[ca] loading...
[ca] certificate ready.
https://192.168.1.135:5443 => http://192.168.1.135:5000
```
- Visiting `http://192.168.1.135:5000` shows the correct non-SSL page.
- Visiting `https://192.168.1.135:5443` doesn't respond and just says "This site can't provide a secure connection" `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`
  - Clicking on the certificate icon in the address bar to inspect things [crashes the computer](http://i.imgur.com/8GntJNJ.jpg) (OSX 10.11.4). But I think the crash is due to a [crappy driver for the USB to gigabit ethernet adapter](https://gist.github.com/MadLittleMods/3005bb13f7e7178e1eaa9f054cc547b0) I am using. Using the external IP for the wifi connection doesn't crash but still produces the SSL error.

![](https://i.imgur.com/n1AEyCo.png)

**Comment by layerssss** [comment]
@MadLittleMods strange, I've reproduced your problem, looking into it.

**Comment by layerssss** [comment]
@MadLittleMods  quickly fixed ✨

**Comment by MadLittleMods** [comment]
@layerssss :+1: Thanks for the quick fix! It is working great :grinning: 

Now I need to figure out a way to mark the cert as trusted without clicking the address bar icon which still crashes when using the gigabit adapter.

**Comment by layerssss** [comment]
Easy, the cert file `.devhttps.ca.crt` is stored in the current directory where you lanched `devhttps`, open it then it will be in the "Keychain Access". Then select "Always trust" when you double click the newly imported entry.

![screen shot 2016-07-08 at 3 26 25 pm](https://cloud.githubusercontent.com/assets/1559832/16676626/652eeaf2-4520-11e6-8ee6-ea13d5224927.png)

In case you cannot find the file in "Finder", you can open it by typing `open .devhttps.ca.crt` into terminal
